#!/bin/bash
# Run this script when opening the project in a new environment
# to set up the Xlator plugin and generate .xlator.local.env with CLAUDE_PLUGIN_ROOT.

set -euo pipefail

# Many install scripts add binaries to ~/.local/bin, so ensure it's on PATH from the start
export PATH="$HOME/.local/bin:$PATH"

# --- Resolve project root ---

if [ -f "xlator.conf" ]; then
    PROJECT_ROOT="$(pwd)"
elif git rev-parse --show-toplevel >/dev/null 2>&1; then
    PROJECT_ROOT="$(git rev-parse --show-toplevel)"
else
    echo "Error: Cannot find project root! Create xlator.conf in the project root." >&2
    exit 1
fi

if [ ! -f "$PROJECT_ROOT/xlator.conf" ]; then
    echo "Error: $PROJECT_ROOT/xlator.conf not found! Create xlator.conf in the project root." >&2
    exit 2
fi

# Load DOMAINS_DIR and other project variables
source "$PROJECT_ROOT/xlator.conf"

# --- Step 1: Install Claude Code, plugins, and uv; write .xlator.local.env ---

setup_xlator_plugin() {
    echo "🙂 1. Updating Claude Code marketplaces and configuring Xlator plugin (writing .xlator.local.env)..."

    if ! command -v claude >/dev/null 2>&1; then
        curl -fsSL https://claude.ai/install.sh | bash
    fi

    # Fortunately, we don't need to authenticate claude to add plugins
    # Append '#tagOrBranch' to the URL to pin a version, e.g. 'main' or 'v1.2.3'
    claude plugin marketplace add https://github.com/navapbc/lockpicks-xlator-plugin.git
    claude plugin install xl@lockpicks-marketplace --scope project

    # Helpful for code generation
    claude plugin marketplace add https://github.com/EveryInc/every-marketplace.git
    claude plugin install compound-engineering@compound-engineering-plugin --scope project

    if ! command -v uv >/dev/null 2>&1; then
        curl -fsSL https://astral.sh/uv/install.sh | sh
    fi

    # CLAUDE_PLUGIN_ROOT is set by Claude Code for hook commands but not other contexts.
    # Persist it so shell scripts and slash commands can use it too.
    CLAUDE_PLUGIN_ROOT=$(claude plugin list --json | uv run python -c '
import sys, json
plugins = json.load(sys.stdin)
xl = next((p for p in plugins if p["id"].startswith("xl@")), None)
print(xl["installPath"] if xl else "", end="")
')
    if [ -z "$CLAUDE_PLUGIN_ROOT" ]; then
        echo "Error: Failed to determine CLAUDE_PLUGIN_ROOT from 'claude plugin list'" >&2
        exit 10
    fi

    if [ ! -d "$CLAUDE_PLUGIN_ROOT" ]; then
        echo "Error: CLAUDE_PLUGIN_ROOT directory does not exist: $CLAUDE_PLUGIN_ROOT" >&2
        exit 11
    fi

    {
        echo "# Auto-generated by $0 script. Required for Xlator to function properly."
        echo "export CLAUDE_PLUGIN_ROOT='${CLAUDE_PLUGIN_ROOT}'"
    } > "$PROJECT_ROOT/.xlator.local.env"
}

# --- Step 2: Set up the domains directory (run from inside $DOMAINS_DIR) ---

setup_domains_dir() {
    echo "😀 3. Creating Python virtual environment and installing dependencies..."
    # 'uv sync' installs the version pinned in .python-version into a local .venv
    uv sync
    . .venv/bin/activate

    echo "😅 4. Initializing opam (if needed, this can take 10 minutes)..."
    if [ ! -d "$HOME/.opam" ]; then
        # Catala supports OCaml versions from 4.14.0 up to 5.4.x
        opam init -y -a -c 5.4.1
        date
    fi
    eval "$(opam env)"

    echo "😄 5. Installing Catala/clerk (if missing, this can take 10 minutes)..."
    if ! command -v clerk >/dev/null 2>&1; then
        opam update && opam install -y catala.1.1.0
        date
    fi

    echo "🤓 6. Creating symlinks in $DOMAINS_DIR..."
    # Allows running xlator scripts directly from the domains directory
    ln -snf "$CLAUDE_PLUGIN_ROOT/xlator" .
    # Provides easy access to the plugin folder for reference
    ln -snf "$CLAUDE_PLUGIN_ROOT" .plugin
}

# --- Main ---

date
setup_xlator_plugin

mkdir -p "$PROJECT_ROOT/$DOMAINS_DIR"
cd "$PROJECT_ROOT/$DOMAINS_DIR"

echo "😊 2. Copying template files to $PROJECT_ROOT/$DOMAINS_DIR ..."
for F in .gitignore pyproject.toml .python-version uv.lock; do
    if [ -f "$F" ] && cmp -s "$CLAUDE_PLUGIN_ROOT/$F" "$F"; then
        : echo "  Skipping (unchanged): $DOMAINS_DIR/$F"
    else
        if [ -f "$F" ]; then
            echo "  Overwriting: $DOMAINS_DIR/$F"
        fi
        cp -v "$CLAUDE_PLUGIN_ROOT/$F" .
    fi
done

setup_domains_dir

if [ ! -f "$PROJECT_ROOT/.gitignore" ] || ! grep -qxF ".xlator.local.env" "$PROJECT_ROOT/.gitignore"; then
    echo "Adding .xlator.local.env to $PROJECT_ROOT/.gitignore"
    echo ".xlator.local.env" >> "$PROJECT_ROOT/.gitignore"
fi

git add .
echo "🤩 Setup complete. Remember to commit the files to git."
