# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en
from . import Exclusion_chain as exclusion_chain

class HouseholdType_Code(Enum):
    A1E = 0
    B1E = 1
    H1E = 2
    A2S = 3
    B2S = 4
    H2S = 5
    A2C = 6
    B2C = 7
    H2C = 8
    NHR = 9

class HouseholdType:
    def __init__(self, code: HouseholdType_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, HouseholdType):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)

class Eligible_Code(Enum):
    Approve = 0
    Deny = 1
    ManualVerification = 2

class Eligible:
    def __init__(self, code: Eligible_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, Eligible):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)

class ReasonCode_Code(Enum):
    IncomeExceedsStandardBoth = 0
    IncomeExceedsStandardClientOnly = 1

class ReasonCode:
    def __init__(self, code: ReasonCode_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, ReasonCode):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)

class DOLRecord:
    def __init__(self, dol_earned_income_available: bool, dol_quarterly_earnings: Money, gross_earned_income: Money, federal_exclusions: Money, eitc_exclusion: Money, irregular_earned_income: Money, student_earned_income: Money, student_monthly_limit: Money, non_needs_based_unearned_remainder: Money, impairment_work_expenses: Money, blind_work_expenses: Money, self_support_exclusion: Money) -> None:
        self.dol_earned_income_available = dol_earned_income_available
        self.dol_quarterly_earnings = dol_quarterly_earnings
        self.gross_earned_income = gross_earned_income
        self.federal_exclusions = federal_exclusions
        self.eitc_exclusion = eitc_exclusion
        self.irregular_earned_income = irregular_earned_income
        self.student_earned_income = student_earned_income
        self.student_monthly_limit = student_monthly_limit
        self.non_needs_based_unearned_remainder = non_needs_based_unearned_remainder
        self.impairment_work_expenses = impairment_work_expenses
        self.blind_work_expenses = blind_work_expenses
        self.self_support_exclusion = self_support_exclusion

    def __eq__(self, other: object) -> bool:
        if isinstance(other, DOLRecord):
            return (self.dol_earned_income_available == other.dol_earned_income_available and self.dol_quarterly_earnings == other.dol_quarterly_earnings and self.gross_earned_income == other.gross_earned_income and self.federal_exclusions == other.federal_exclusions and self.eitc_exclusion == other.eitc_exclusion and self.irregular_earned_income == other.irregular_earned_income and self.student_earned_income == other.student_earned_income and self.student_monthly_limit == other.student_monthly_limit and self.non_needs_based_unearned_remainder == other.non_needs_based_unearned_remainder and self.impairment_work_expenses == other.impairment_work_expenses and self.blind_work_expenses == other.blind_work_expenses and self.self_support_exclusion == other.self_support_exclusion)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "DOLRecord(dol_earned_income_available={},dol_quarterly_earnings={},gross_earned_income={},federal_exclusions={},eitc_exclusion={},irregular_earned_income={},student_earned_income={},student_monthly_limit={},non_needs_based_unearned_remainder={},impairment_work_expenses={},blind_work_expenses={},self_support_exclusion={})".format(self.dol_earned_income_available, self.dol_quarterly_earnings, self.gross_earned_income, self.federal_exclusions, self.eitc_exclusion, self.irregular_earned_income, self.student_earned_income, self.student_monthly_limit, self.non_needs_based_unearned_remainder, self.impairment_work_expenses, self.blind_work_expenses, self.self_support_exclusion)

class ClientData:
    def __init__(self, gross_earned_income: Money, federal_exclusions: Money, eitc_exclusion: Money, irregular_earned_income: Money, student_earned_income: Money, student_monthly_limit: Money, non_needs_based_unearned_remainder: Money, impairment_work_expenses: Money, blind_work_expenses: Money, self_support_exclusion: Money, household_type: HouseholdType, benefit_year: Integer) -> None:
        self.gross_earned_income = gross_earned_income
        self.federal_exclusions = federal_exclusions
        self.eitc_exclusion = eitc_exclusion
        self.irregular_earned_income = irregular_earned_income
        self.student_earned_income = student_earned_income
        self.student_monthly_limit = student_monthly_limit
        self.non_needs_based_unearned_remainder = non_needs_based_unearned_remainder
        self.impairment_work_expenses = impairment_work_expenses
        self.blind_work_expenses = blind_work_expenses
        self.self_support_exclusion = self_support_exclusion
        self.household_type = household_type
        self.benefit_year = benefit_year

    def __eq__(self, other: object) -> bool:
        if isinstance(other, ClientData):
            return (self.gross_earned_income == other.gross_earned_income and self.federal_exclusions == other.federal_exclusions and self.eitc_exclusion == other.eitc_exclusion and self.irregular_earned_income == other.irregular_earned_income and self.student_earned_income == other.student_earned_income and self.student_monthly_limit == other.student_monthly_limit and self.non_needs_based_unearned_remainder == other.non_needs_based_unearned_remainder and self.impairment_work_expenses == other.impairment_work_expenses and self.blind_work_expenses == other.blind_work_expenses and self.self_support_exclusion == other.self_support_exclusion and self.household_type == other.household_type and self.benefit_year == other.benefit_year)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "ClientData(gross_earned_income={},federal_exclusions={},eitc_exclusion={},irregular_earned_income={},student_earned_income={},student_monthly_limit={},non_needs_based_unearned_remainder={},impairment_work_expenses={},blind_work_expenses={},self_support_exclusion={},household_type={},benefit_year={})".format(self.gross_earned_income, self.federal_exclusions, self.eitc_exclusion, self.irregular_earned_income, self.student_earned_income, self.student_monthly_limit, self.non_needs_based_unearned_remainder, self.impairment_work_expenses, self.blind_work_expenses, self.self_support_exclusion, self.household_type, self.benefit_year)

class ReasonEntry:
    def __init__(self, triggered: bool, code: ReasonCode) -> None:
        self.triggered = triggered
        self.code = code

    def __eq__(self, other: object) -> bool:
        if isinstance(other, ReasonEntry):
            return (self.triggered == other.triggered and self.code == other.code)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "ReasonEntry(triggered={},code={})".format(self.triggered, self.code)

class EligibilityDecision:
    def __init__(self, client_result: exclusion_chain.ExclusionChainDecision, dol_result: exclusion_chain.ExclusionChainDecision, dol_avg_monthly_income: Money, is_compatible: bool, income_limit: Money, eligible: Eligible, reasons: List[ReasonCode]) -> None:
        self.client_result = client_result
        self.dol_result = dol_result
        self.dol_avg_monthly_income = dol_avg_monthly_income
        self.is_compatible = is_compatible
        self.income_limit = income_limit
        self.eligible = eligible
        self.reasons = reasons

    def __eq__(self, other: object) -> bool:
        if isinstance(other, EligibilityDecision):
            return (self.client_result == other.client_result and self.dol_result == other.dol_result and self.dol_avg_monthly_income == other.dol_avg_monthly_income and self.is_compatible == other.is_compatible and self.income_limit == other.income_limit and self.eligible == other.eligible and self.reasons == other.reasons)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "EligibilityDecision(client_result={},dol_result={},dol_avg_monthly_income={},is_compatible={},income_limit={},eligible={},reasons={})".format(self.client_result, self.dol_result, self.dol_avg_monthly_income, self.is_compatible, self.income_limit, self.eligible, self.reasons)

class EligibilityDecisionIn:
    def __init__(self, client_data_in: ClientData, d_o_l_record_in: DOLRecord) -> None:
        self.client_data_in = client_data_in
        self.d_o_l_record_in = d_o_l_record_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, EligibilityDecisionIn):
            return (self.client_data_in == other.client_data_in and self.d_o_l_record_in == other.d_o_l_record_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "EligibilityDecisionIn(client_data_in={},d_o_l_record_in={})".format(self.client_data_in, self.d_o_l_record_in)


def eligibility_decision(eligibility_decision_in:EligibilityDecisionIn):
    client_data = (eligibility_decision_in.client_data_in)
    d_o_l_record = (eligibility_decision_in.d_o_l_record_in)
    income_limit__3 = (client_data.household_type)
    if income_limit__3.code == HouseholdType_Code.A1E:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.B1E:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.H1E:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.A2S:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.B2S:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.H2S:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.A2C:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.B2C:
        income_limit__2 = (False)
    elif income_limit__3.code == HouseholdType_Code.H2C:
        income_limit__2 = (True)
    elif income_limit__3.code == HouseholdType_Code.NHR:
        income_limit__2 = (False)
    if (income_limit__2 and (client_data.benefit_year == Integer(2024))):
        pos = (SourcePosition(filename="eligibility.catala_en", start_line=330, start_column=24, end_line=330, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
        income_limit__1 = (Option((Money(Integer(259300)), pos)))
    else:
        income_limit__5 = (client_data.household_type)
        if income_limit__5.code == HouseholdType_Code.A1E:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.B1E:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.H1E:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.A2S:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.B2S:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.H2S:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.A2C:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.B2C:
            income_limit__4 = (True)
        elif income_limit__5.code == HouseholdType_Code.H2C:
            income_limit__4 = (False)
        elif income_limit__5.code == HouseholdType_Code.NHR:
            income_limit__4 = (False)
        if (income_limit__4 and (client_data.benefit_year == Integer(2024))):
            pos = (SourcePosition(filename="eligibility.catala_en", start_line=325, start_column=24, end_line=325, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
            income_limit__1 = (Option((Money(Integer(259300)), pos)))
        else:
            income_limit__7 = (client_data.household_type)
            if income_limit__7.code == HouseholdType_Code.A1E:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.B1E:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.H1E:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.A2S:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.B2S:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.H2S:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.A2C:
                income_limit__6 = (True)
            elif income_limit__7.code == HouseholdType_Code.B2C:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.H2C:
                income_limit__6 = (False)
            elif income_limit__7.code == HouseholdType_Code.NHR:
                income_limit__6 = (False)
            if (income_limit__6 and (client_data.benefit_year == Integer(2024))):
                pos = (SourcePosition(filename="eligibility.catala_en", start_line=320, start_column=24, end_line=320, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                income_limit__1 = (Option((Money(Integer(259300)), pos)))
            else:
                income_limit__9 = (client_data.household_type)
                if income_limit__9.code == HouseholdType_Code.A1E:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.B1E:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.H1E:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.A2S:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.B2S:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.H2S:
                    income_limit__8 = (True)
                elif income_limit__9.code == HouseholdType_Code.A2C:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.B2C:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.H2C:
                    income_limit__8 = (False)
                elif income_limit__9.code == HouseholdType_Code.NHR:
                    income_limit__8 = (False)
                if (income_limit__8 and (client_data.benefit_year == Integer(2024))):
                    pos = (SourcePosition(filename="eligibility.catala_en", start_line=315, start_column=24, end_line=315, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                    income_limit__1 = (Option((Money(Integer(259300)), pos)))
                else:
                    income_limit__11 = (client_data.household_type)
                    if income_limit__11.code == HouseholdType_Code.A1E:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.B1E:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.H1E:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.A2S:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.B2S:
                        income_limit__10 = (True)
                    elif income_limit__11.code == HouseholdType_Code.H2S:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.A2C:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.B2C:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.H2C:
                        income_limit__10 = (False)
                    elif income_limit__11.code == HouseholdType_Code.NHR:
                        income_limit__10 = (False)
                    if (income_limit__10 and (client_data.benefit_year == Integer(2024))):
                        pos = (SourcePosition(filename="eligibility.catala_en", start_line=310, start_column=24, end_line=310, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                        income_limit__1 = (Option((Money(Integer(259300)), pos)))
                    else:
                        income_limit__13 = (client_data.household_type)
                        if income_limit__13.code == HouseholdType_Code.A1E:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.B1E:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.H1E:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.A2S:
                            income_limit__12 = (True)
                        elif income_limit__13.code == HouseholdType_Code.B2S:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.H2S:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.A2C:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.B2C:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.H2C:
                            income_limit__12 = (False)
                        elif income_limit__13.code == HouseholdType_Code.NHR:
                            income_limit__12 = (False)
                        if (income_limit__12 and (client_data.benefit_year == Integer(2024))):
                            pos = (SourcePosition(filename="eligibility.catala_en", start_line=305, start_column=24, end_line=305, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                            income_limit__1 = (Option((Money(Integer(259300)), pos)))
                        else:
                            income_limit__1 = (Option(None))
    income_limit__6 = (client_data.household_type)
    if income_limit__6.code == HouseholdType_Code.A1E:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.B1E:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.H1E:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.A2S:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.B2S:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.H2S:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.A2C:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.B2C:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.H2C:
        income_limit__5 = (False)
    elif income_limit__6.code == HouseholdType_Code.NHR:
        income_limit__5 = (True)
    if (income_limit__5 and (client_data.benefit_year == Integer(2024))):
        pos = (SourcePosition(filename="eligibility.catala_en", start_line=335, start_column=24, end_line=335, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
        income_limit__4 = (Option((Money(Integer(175100)), pos)))
    else:
        income_limit__8 = (client_data.household_type)
        if income_limit__8.code == HouseholdType_Code.A1E:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.B1E:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.H1E:
            income_limit__7 = (True)
        elif income_limit__8.code == HouseholdType_Code.A2S:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.B2S:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.H2S:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.A2C:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.B2C:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.H2C:
            income_limit__7 = (False)
        elif income_limit__8.code == HouseholdType_Code.NHR:
            income_limit__7 = (False)
        if (income_limit__7 and (client_data.benefit_year == Integer(2024))):
            pos = (SourcePosition(filename="eligibility.catala_en", start_line=300, start_column=24, end_line=300, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
            income_limit__4 = (Option((Money(Integer(175100)), pos)))
        else:
            income_limit__10 = (client_data.household_type)
            if income_limit__10.code == HouseholdType_Code.A1E:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.B1E:
                income_limit__9 = (True)
            elif income_limit__10.code == HouseholdType_Code.H1E:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.A2S:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.B2S:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.H2S:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.A2C:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.B2C:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.H2C:
                income_limit__9 = (False)
            elif income_limit__10.code == HouseholdType_Code.NHR:
                income_limit__9 = (False)
            if (income_limit__9 and (client_data.benefit_year == Integer(2024))):
                pos = (SourcePosition(filename="eligibility.catala_en", start_line=295, start_column=24, end_line=295, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                income_limit__4 = (Option((Money(Integer(175100)), pos)))
            else:
                income_limit__12 = (client_data.household_type)
                if income_limit__12.code == HouseholdType_Code.A1E:
                    income_limit__11 = (True)
                elif income_limit__12.code == HouseholdType_Code.B1E:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.H1E:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.A2S:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.B2S:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.H2S:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.A2C:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.B2C:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.H2C:
                    income_limit__11 = (False)
                elif income_limit__12.code == HouseholdType_Code.NHR:
                    income_limit__11 = (False)
                if (income_limit__11 and (client_data.benefit_year == Integer(2024))):
                    pos = (SourcePosition(filename="eligibility.catala_en", start_line=290, start_column=24, end_line=290, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                    income_limit__4 = (Option((Money(Integer(175100)), pos)))
                else:
                    income_limit__4 = (Option(None))
    income_limit__9 = (client_data.household_type)
    if income_limit__9.code == HouseholdType_Code.A1E:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.B1E:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.H1E:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.A2S:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.B2S:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.H2S:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.A2C:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.B2C:
        income_limit__8 = (False)
    elif income_limit__9.code == HouseholdType_Code.H2C:
        income_limit__8 = (True)
    elif income_limit__9.code == HouseholdType_Code.NHR:
        income_limit__8 = (False)
    if (income_limit__8 and (client_data.benefit_year == Integer(2025))):
        pos = (SourcePosition(filename="eligibility.catala_en", start_line=380, start_column=24, end_line=380, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
        income_limit__7 = (Option((Money(Integer(265800)), pos)))
    else:
        income_limit__11 = (client_data.household_type)
        if income_limit__11.code == HouseholdType_Code.A1E:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.B1E:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.H1E:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.A2S:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.B2S:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.H2S:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.A2C:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.B2C:
            income_limit__10 = (True)
        elif income_limit__11.code == HouseholdType_Code.H2C:
            income_limit__10 = (False)
        elif income_limit__11.code == HouseholdType_Code.NHR:
            income_limit__10 = (False)
        if (income_limit__10 and (client_data.benefit_year == Integer(2025))):
            pos = (SourcePosition(filename="eligibility.catala_en", start_line=375, start_column=24, end_line=375, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
            income_limit__7 = (Option((Money(Integer(265800)), pos)))
        else:
            income_limit__13 = (client_data.household_type)
            if income_limit__13.code == HouseholdType_Code.A1E:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.B1E:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.H1E:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.A2S:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.B2S:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.H2S:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.A2C:
                income_limit__12 = (True)
            elif income_limit__13.code == HouseholdType_Code.B2C:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.H2C:
                income_limit__12 = (False)
            elif income_limit__13.code == HouseholdType_Code.NHR:
                income_limit__12 = (False)
            if (income_limit__12 and (client_data.benefit_year == Integer(2025))):
                pos = (SourcePosition(filename="eligibility.catala_en", start_line=370, start_column=24, end_line=370, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                income_limit__7 = (Option((Money(Integer(265800)), pos)))
            else:
                income_limit__15 = (client_data.household_type)
                if income_limit__15.code == HouseholdType_Code.A1E:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.B1E:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.H1E:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.A2S:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.B2S:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.H2S:
                    income_limit__14 = (True)
                elif income_limit__15.code == HouseholdType_Code.A2C:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.B2C:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.H2C:
                    income_limit__14 = (False)
                elif income_limit__15.code == HouseholdType_Code.NHR:
                    income_limit__14 = (False)
                if (income_limit__14 and (client_data.benefit_year == Integer(2025))):
                    pos = (SourcePosition(filename="eligibility.catala_en", start_line=365, start_column=24, end_line=365, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                    income_limit__7 = (Option((Money(Integer(265800)), pos)))
                else:
                    income_limit__17 = (client_data.household_type)
                    if income_limit__17.code == HouseholdType_Code.A1E:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.B1E:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.H1E:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.A2S:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.B2S:
                        income_limit__16 = (True)
                    elif income_limit__17.code == HouseholdType_Code.H2S:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.A2C:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.B2C:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.H2C:
                        income_limit__16 = (False)
                    elif income_limit__17.code == HouseholdType_Code.NHR:
                        income_limit__16 = (False)
                    if (income_limit__16 and (client_data.benefit_year == Integer(2025))):
                        pos = (SourcePosition(filename="eligibility.catala_en", start_line=360, start_column=24, end_line=360, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                        income_limit__7 = (Option((Money(Integer(265800)), pos)))
                    else:
                        income_limit__19 = (client_data.household_type)
                        if income_limit__19.code == HouseholdType_Code.A1E:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.B1E:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.H1E:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.A2S:
                            income_limit__18 = (True)
                        elif income_limit__19.code == HouseholdType_Code.B2S:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.H2S:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.A2C:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.B2C:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.H2C:
                            income_limit__18 = (False)
                        elif income_limit__19.code == HouseholdType_Code.NHR:
                            income_limit__18 = (False)
                        if (income_limit__18 and (client_data.benefit_year == Integer(2025))):
                            pos = (SourcePosition(filename="eligibility.catala_en", start_line=355, start_column=24, end_line=355, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                            income_limit__7 = (Option((Money(Integer(265800)), pos)))
                        else:
                            income_limit__7 = (Option(None))
    income_limit__12 = (client_data.household_type)
    if income_limit__12.code == HouseholdType_Code.A1E:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.B1E:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.H1E:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.A2S:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.B2S:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.H2S:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.A2C:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.B2C:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.H2C:
        income_limit__11 = (False)
    elif income_limit__12.code == HouseholdType_Code.NHR:
        income_limit__11 = (True)
    if (income_limit__11 and (client_data.benefit_year == Integer(2025))):
        pos = (SourcePosition(filename="eligibility.catala_en", start_line=385, start_column=24, end_line=385, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
        income_limit__10 = (Option((Money(Integer(179500)), pos)))
    else:
        income_limit__14 = (client_data.household_type)
        if income_limit__14.code == HouseholdType_Code.A1E:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.B1E:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.H1E:
            income_limit__13 = (True)
        elif income_limit__14.code == HouseholdType_Code.A2S:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.B2S:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.H2S:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.A2C:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.B2C:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.H2C:
            income_limit__13 = (False)
        elif income_limit__14.code == HouseholdType_Code.NHR:
            income_limit__13 = (False)
        if (income_limit__13 and (client_data.benefit_year == Integer(2025))):
            pos = (SourcePosition(filename="eligibility.catala_en", start_line=350, start_column=24, end_line=350, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
            income_limit__10 = (Option((Money(Integer(179500)), pos)))
        else:
            income_limit__16 = (client_data.household_type)
            if income_limit__16.code == HouseholdType_Code.A1E:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.B1E:
                income_limit__15 = (True)
            elif income_limit__16.code == HouseholdType_Code.H1E:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.A2S:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.B2S:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.H2S:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.A2C:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.B2C:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.H2C:
                income_limit__15 = (False)
            elif income_limit__16.code == HouseholdType_Code.NHR:
                income_limit__15 = (False)
            if (income_limit__15 and (client_data.benefit_year == Integer(2025))):
                pos = (SourcePosition(filename="eligibility.catala_en", start_line=345, start_column=24, end_line=345, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                income_limit__10 = (Option((Money(Integer(179500)), pos)))
            else:
                income_limit__18 = (client_data.household_type)
                if income_limit__18.code == HouseholdType_Code.A1E:
                    income_limit__17 = (True)
                elif income_limit__18.code == HouseholdType_Code.B1E:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.H1E:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.A2S:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.B2S:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.H2S:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.A2C:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.B2C:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.H2C:
                    income_limit__17 = (False)
                elif income_limit__18.code == HouseholdType_Code.NHR:
                    income_limit__17 = (False)
                if (income_limit__17 and (client_data.benefit_year == Integer(2025))):
                    pos = (SourcePosition(filename="eligibility.catala_en", start_line=340, start_column=24, end_line=340, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                    income_limit__10 = (Option((Money(Integer(179500)), pos)))
                else:
                    income_limit__10 = (Option(None))
    income_limit__15 = (client_data.household_type)
    if income_limit__15.code == HouseholdType_Code.A1E:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.B1E:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.H1E:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.A2S:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.B2S:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.H2S:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.A2C:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.B2C:
        income_limit__14 = (False)
    elif income_limit__15.code == HouseholdType_Code.H2C:
        income_limit__14 = (True)
    elif income_limit__15.code == HouseholdType_Code.NHR:
        income_limit__14 = (False)
    if (income_limit__14 and (client_data.benefit_year == Integer(2026))):
        pos = (SourcePosition(filename="eligibility.catala_en", start_line=430, start_column=24, end_line=430, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
        income_limit__13 = (Option((Money(Integer(273200)), pos)))
    else:
        income_limit__17 = (client_data.household_type)
        if income_limit__17.code == HouseholdType_Code.A1E:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.B1E:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.H1E:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.A2S:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.B2S:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.H2S:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.A2C:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.B2C:
            income_limit__16 = (True)
        elif income_limit__17.code == HouseholdType_Code.H2C:
            income_limit__16 = (False)
        elif income_limit__17.code == HouseholdType_Code.NHR:
            income_limit__16 = (False)
        if (income_limit__16 and (client_data.benefit_year == Integer(2026))):
            pos = (SourcePosition(filename="eligibility.catala_en", start_line=425, start_column=24, end_line=425, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
            income_limit__13 = (Option((Money(Integer(273200)), pos)))
        else:
            income_limit__19 = (client_data.household_type)
            if income_limit__19.code == HouseholdType_Code.A1E:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.B1E:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.H1E:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.A2S:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.B2S:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.H2S:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.A2C:
                income_limit__18 = (True)
            elif income_limit__19.code == HouseholdType_Code.B2C:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.H2C:
                income_limit__18 = (False)
            elif income_limit__19.code == HouseholdType_Code.NHR:
                income_limit__18 = (False)
            if (income_limit__18 and (client_data.benefit_year == Integer(2026))):
                pos = (SourcePosition(filename="eligibility.catala_en", start_line=420, start_column=24, end_line=420, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                income_limit__13 = (Option((Money(Integer(273200)), pos)))
            else:
                income_limit__21 = (client_data.household_type)
                if income_limit__21.code == HouseholdType_Code.A1E:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.B1E:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.H1E:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.A2S:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.B2S:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.H2S:
                    income_limit__20 = (True)
                elif income_limit__21.code == HouseholdType_Code.A2C:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.B2C:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.H2C:
                    income_limit__20 = (False)
                elif income_limit__21.code == HouseholdType_Code.NHR:
                    income_limit__20 = (False)
                if (income_limit__20 and (client_data.benefit_year == Integer(2026))):
                    pos = (SourcePosition(filename="eligibility.catala_en", start_line=415, start_column=24, end_line=415, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                    income_limit__13 = (Option((Money(Integer(273200)), pos)))
                else:
                    income_limit__23 = (client_data.household_type)
                    if income_limit__23.code == HouseholdType_Code.A1E:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.B1E:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.H1E:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.A2S:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.B2S:
                        income_limit__22 = (True)
                    elif income_limit__23.code == HouseholdType_Code.H2S:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.A2C:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.B2C:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.H2C:
                        income_limit__22 = (False)
                    elif income_limit__23.code == HouseholdType_Code.NHR:
                        income_limit__22 = (False)
                    if (income_limit__22 and (client_data.benefit_year == Integer(2026))):
                        pos = (SourcePosition(filename="eligibility.catala_en", start_line=410, start_column=24, end_line=410, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                        income_limit__13 = (Option((Money(Integer(273200)), pos)))
                    else:
                        income_limit__25 = (client_data.household_type)
                        if income_limit__25.code == HouseholdType_Code.A1E:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.B1E:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.H1E:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.A2S:
                            income_limit__24 = (True)
                        elif income_limit__25.code == HouseholdType_Code.B2S:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.H2S:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.A2C:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.B2C:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.H2C:
                            income_limit__24 = (False)
                        elif income_limit__25.code == HouseholdType_Code.NHR:
                            income_limit__24 = (False)
                        if (income_limit__24 and (client_data.benefit_year == Integer(2026))):
                            pos = (SourcePosition(filename="eligibility.catala_en", start_line=405, start_column=24, end_line=405, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                            income_limit__13 = (Option((Money(Integer(273200)), pos)))
                        else:
                            income_limit__13 = (Option(None))
    income_limit__18 = (client_data.household_type)
    if income_limit__18.code == HouseholdType_Code.A1E:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.B1E:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.H1E:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.A2S:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.B2S:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.H2S:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.A2C:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.B2C:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.H2C:
        income_limit__17 = (False)
    elif income_limit__18.code == HouseholdType_Code.NHR:
        income_limit__17 = (True)
    if (income_limit__17 and (client_data.benefit_year == Integer(2026))):
        pos = (SourcePosition(filename="eligibility.catala_en", start_line=435, start_column=24, end_line=435, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
        income_limit__16 = (Option((Money(Integer(184500)), pos)))
    else:
        income_limit__20 = (client_data.household_type)
        if income_limit__20.code == HouseholdType_Code.A1E:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.B1E:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.H1E:
            income_limit__19 = (True)
        elif income_limit__20.code == HouseholdType_Code.A2S:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.B2S:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.H2S:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.A2C:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.B2C:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.H2C:
            income_limit__19 = (False)
        elif income_limit__20.code == HouseholdType_Code.NHR:
            income_limit__19 = (False)
        if (income_limit__19 and (client_data.benefit_year == Integer(2026))):
            pos = (SourcePosition(filename="eligibility.catala_en", start_line=400, start_column=24, end_line=400, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
            income_limit__16 = (Option((Money(Integer(184500)), pos)))
        else:
            income_limit__22 = (client_data.household_type)
            if income_limit__22.code == HouseholdType_Code.A1E:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.B1E:
                income_limit__21 = (True)
            elif income_limit__22.code == HouseholdType_Code.H1E:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.A2S:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.B2S:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.H2S:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.A2C:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.B2C:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.H2C:
                income_limit__21 = (False)
            elif income_limit__22.code == HouseholdType_Code.NHR:
                income_limit__21 = (False)
            if (income_limit__21 and (client_data.benefit_year == Integer(2026))):
                pos = (SourcePosition(filename="eligibility.catala_en", start_line=395, start_column=24, end_line=395, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                income_limit__16 = (Option((Money(Integer(184500)), pos)))
            else:
                income_limit__24 = (client_data.household_type)
                if income_limit__24.code == HouseholdType_Code.A1E:
                    income_limit__23 = (True)
                elif income_limit__24.code == HouseholdType_Code.B1E:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.H1E:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.A2S:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.B2S:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.H2S:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.A2C:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.B2C:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.H2C:
                    income_limit__23 = (False)
                elif income_limit__24.code == HouseholdType_Code.NHR:
                    income_limit__23 = (False)
                if (income_limit__23 and (client_data.benefit_year == Integer(2026))):
                    pos = (SourcePosition(filename="eligibility.catala_en", start_line=390, start_column=24, end_line=390, end_column=30, law_headings=["income_limit", "Table Lookups", "Eligibility"]))
                    income_limit__16 = (Option((Money(Integer(184500)), pos)))
                else:
                    income_limit__16 = (Option(None))
    income_limit__19 = (handle_exceptions([income_limit__1, income_limit__4, income_limit__7, income_limit__10, income_limit__13, income_limit__16]))
    if income_limit__19.value is not None:
        income_limit = (income_limit__19.value[0])
    else:
        pos = (SourcePosition(filename="eligibility.catala_en", start_line=224, start_column=10, end_line=224, end_column=22, law_headings=["self_support_exclusion", "Declarations", "Eligibility"]))
        raise NoValue(pos, None)
    result = (exclusion_chain.exclusion_chain_decision(exclusion_chain.ExclusionChainDecisionIn(gross_earned_income_in = client_data.gross_earned_income, federal_exclusions_in = client_data.federal_exclusions, eitc_exclusion_in = client_data.eitc_exclusion, irregular_earned_income_in = client_data.irregular_earned_income, student_earned_income_in = client_data.student_earned_income, student_monthly_limit_in = client_data.student_monthly_limit, non_needs_based_unearned_remainder_in = client_data.non_needs_based_unearned_remainder, impairment_work_expenses_in = client_data.impairment_work_expenses, blind_work_expenses_in = client_data.blind_work_expenses, self_support_exclusion_in = client_data.self_support_exclusion)))
    client_result = (exclusion_chain.ExclusionChainDecision(after_65 = result.after_65, after_irwe = result.after_irwe, after_half = result.after_half, after_blind = result.after_blind, adjusted_earned_income = result.adjusted_earned_income))
    pos = (SourcePosition(filename="eligibility.catala_en", start_line=450, start_column=41, end_line=450, end_column=42, law_headings=["dol_avg_monthly_income", "Computed Values", "Eligibility"]))
    dol_avg_monthly_income = (div(pos, d_o_l_record.dol_quarterly_earnings, Integer(3)))
    result__1 = (exclusion_chain.exclusion_chain_decision(exclusion_chain.ExclusionChainDecisionIn(gross_earned_income_in = d_o_l_record.gross_earned_income, federal_exclusions_in = d_o_l_record.federal_exclusions, eitc_exclusion_in = d_o_l_record.eitc_exclusion, irregular_earned_income_in = d_o_l_record.irregular_earned_income, student_earned_income_in = d_o_l_record.student_earned_income, student_monthly_limit_in = d_o_l_record.student_monthly_limit, non_needs_based_unearned_remainder_in = d_o_l_record.non_needs_based_unearned_remainder, impairment_work_expenses_in = d_o_l_record.impairment_work_expenses, blind_work_expenses_in = d_o_l_record.blind_work_expenses, self_support_exclusion_in = d_o_l_record.self_support_exclusion)))
    dol_result = (exclusion_chain.ExclusionChainDecision(after_65 = result__1.after_65, after_irwe = result__1.after_irwe, after_half = result__1.after_half, after_blind = result__1.after_blind, adjusted_earned_income = result__1.adjusted_earned_income))
    if ((dol_result.adjusted_earned_income - client_result.adjusted_earned_income) >= Money(Integer(0))):
        is_compatible__1 = ((dol_result.adjusted_earned_income - client_result.adjusted_earned_income))
    else:
        is_compatible__1 = ((Money(Integer(0)) - (dol_result.adjusted_earned_income - client_result.adjusted_earned_income)))
    is_compatible = ((is_compatible__1 <= (client_result.adjusted_earned_income * decimal_of_string("1/10"))))
    if (d_o_l_record.dol_earned_income_available and ((client_result.adjusted_earned_income > income_limit) and (dol_result.adjusted_earned_income <= income_limit))):
        pos__1 = (SourcePosition(filename="eligibility.catala_en", start_line=531, start_column=17, end_line=531, end_column=26, law_headings=["AK-ELIG-DENY-002", "Rules", "Eligibility"]))
        deny_rule_2_triggered = ((True, pos__1)[0])
    else:
        pos__1 = (SourcePosition(filename="eligibility.catala_en", start_line=217, start_column=12, end_line=217, end_column=33, law_headings=["self_support_exclusion", "Declarations", "Eligibility"]))
        deny_rule_2_triggered = ((False, pos__1)[0])
    if (d_o_l_record.dol_earned_income_available and ((client_result.adjusted_earned_income > income_limit) and (dol_result.adjusted_earned_income > income_limit))):
        pos__1 = (SourcePosition(filename="eligibility.catala_en", start_line=509, start_column=17, end_line=509, end_column=26, law_headings=["AK-ELIG-DENY-001", "Rules", "Eligibility"]))
        deny_rule_1_triggered = ((True, pos__1)[0])
    else:
        pos__1 = (SourcePosition(filename="eligibility.catala_en", start_line=216, start_column=12, end_line=216, end_column=33, law_headings=["self_support_exclusion", "Declarations", "Eligibility"]))
        deny_rule_1_triggered = ((False, pos__1)[0])
    if (not d_o_l_record.dol_earned_income_available or ((client_result.adjusted_earned_income <= income_limit) and ((dol_result.adjusted_earned_income > income_limit) and not is_compatible))):
        pos__1 = (SourcePosition(filename="eligibility.catala_en", start_line=485, start_column=17, end_line=485, end_column=26, law_headings=["manual_verification_required", "Computed Values", "Eligibility"]))
        manual_verification_required = ((True, pos__1)[0])
    else:
        pos__1 = (SourcePosition(filename="eligibility.catala_en", start_line=215, start_column=12, end_line=215, end_column=40, law_headings=["self_support_exclusion", "Declarations", "Eligibility"]))
        manual_verification_required = ((False, pos__1)[0])
    all_reason_entries = ([ReasonEntry(triggered = deny_rule_1_triggered, code = ReasonCode(ReasonCode_Code.IncomeExceedsStandardBoth, Unit())), ReasonEntry(triggered = deny_rule_2_triggered, code = ReasonCode(ReasonCode_Code.IncomeExceedsStandardClientOnly, Unit()))])
    def reasons__1(entry:ReasonEntry):
        return entry.code
    def reasons__2(e:ReasonEntry):
        return e.triggered
    reasons = (list_map(reasons__1, list_filter(reasons__2, all_reason_entries)))
    if (list_length(reasons) > Integer(0)):
        eligible = (Eligible(Eligible_Code.Deny, Unit()))
    elif manual_verification_required:
        eligible = (Eligible(Eligible_Code.ManualVerification, Unit()))
    else:
        eligible = (Eligible(Eligible_Code.Approve, Unit()))
    return EligibilityDecision(client_result = client_result, dol_result = dol_result, dol_avg_monthly_income = dol_avg_monthly_income, is_compatible = is_compatible, income_limit = income_limit, eligible = eligible, reasons = reasons)
