# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en

class ExclusionChainDecision:
    def __init__(self, after_65: Money, after_irwe: Money, after_half: Money, after_blind: Money, adjusted_earned_income: Money) -> None:
        self.after_65 = after_65
        self.after_irwe = after_irwe
        self.after_half = after_half
        self.after_blind = after_blind
        self.adjusted_earned_income = adjusted_earned_income

    def __eq__(self, other: object) -> bool:
        if isinstance(other, ExclusionChainDecision):
            return (self.after_65 == other.after_65 and self.after_irwe == other.after_irwe and self.after_half == other.after_half and self.after_blind == other.after_blind and self.adjusted_earned_income == other.adjusted_earned_income)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "ExclusionChainDecision(after_65={},after_irwe={},after_half={},after_blind={},adjusted_earned_income={})".format(self.after_65, self.after_irwe, self.after_half, self.after_blind, self.adjusted_earned_income)

class ExclusionChainDecisionIn:
    def __init__(self, gross_earned_income_in: Money, federal_exclusions_in: Money, eitc_exclusion_in: Money, irregular_earned_income_in: Money, student_earned_income_in: Money, student_monthly_limit_in: Money, non_needs_based_unearned_remainder_in: Money, impairment_work_expenses_in: Money, blind_work_expenses_in: Money, self_support_exclusion_in: Money) -> None:
        self.gross_earned_income_in = gross_earned_income_in
        self.federal_exclusions_in = federal_exclusions_in
        self.eitc_exclusion_in = eitc_exclusion_in
        self.irregular_earned_income_in = irregular_earned_income_in
        self.student_earned_income_in = student_earned_income_in
        self.student_monthly_limit_in = student_monthly_limit_in
        self.non_needs_based_unearned_remainder_in = non_needs_based_unearned_remainder_in
        self.impairment_work_expenses_in = impairment_work_expenses_in
        self.blind_work_expenses_in = blind_work_expenses_in
        self.self_support_exclusion_in = self_support_exclusion_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, ExclusionChainDecisionIn):
            return (self.gross_earned_income_in == other.gross_earned_income_in and self.federal_exclusions_in == other.federal_exclusions_in and self.eitc_exclusion_in == other.eitc_exclusion_in and self.irregular_earned_income_in == other.irregular_earned_income_in and self.student_earned_income_in == other.student_earned_income_in and self.student_monthly_limit_in == other.student_monthly_limit_in and self.non_needs_based_unearned_remainder_in == other.non_needs_based_unearned_remainder_in and self.impairment_work_expenses_in == other.impairment_work_expenses_in and self.blind_work_expenses_in == other.blind_work_expenses_in and self.self_support_exclusion_in == other.self_support_exclusion_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "ExclusionChainDecisionIn(gross_earned_income_in={},federal_exclusions_in={},eitc_exclusion_in={},irregular_earned_income_in={},student_earned_income_in={},student_monthly_limit_in={},non_needs_based_unearned_remainder_in={},impairment_work_expenses_in={},blind_work_expenses_in={},self_support_exclusion_in={})".format(self.gross_earned_income_in, self.federal_exclusions_in, self.eitc_exclusion_in, self.irregular_earned_income_in, self.student_earned_income_in, self.student_monthly_limit_in, self.non_needs_based_unearned_remainder_in, self.impairment_work_expenses_in, self.blind_work_expenses_in, self.self_support_exclusion_in)


def exclusion_chain_decision(exclusion_chain_decision_in:ExclusionChainDecisionIn):
    gross_earned_income = (exclusion_chain_decision_in.gross_earned_income_in)
    federal_exclusions = (exclusion_chain_decision_in.federal_exclusions_in)
    eitc_exclusion = (exclusion_chain_decision_in.eitc_exclusion_in)
    irregular_earned_income = (exclusion_chain_decision_in.irregular_earned_income_in)
    student_earned_income = (exclusion_chain_decision_in.student_earned_income_in)
    student_monthly_limit = (exclusion_chain_decision_in.student_monthly_limit_in)
    non_needs_based_unearned_remainder = (exclusion_chain_decision_in.non_needs_based_unearned_remainder_in)
    impairment_work_expenses = (exclusion_chain_decision_in.impairment_work_expenses_in)
    blind_work_expenses = (exclusion_chain_decision_in.blind_work_expenses_in)
    self_support_exclusion = (exclusion_chain_decision_in.self_support_exclusion_in)
    after_federal = ((gross_earned_income - federal_exclusions))
    after_eitc = ((after_federal - eitc_exclusion))
    if (irregular_earned_income <= Money(Integer(1000))):
        after_irregular__1 = (irregular_earned_income)
    else:
        after_irregular__1 = (Money(Integer(1000)))
    after_irregular = ((after_eitc - after_irregular__1))
    if (student_earned_income <= student_monthly_limit):
        after_student__1 = (student_earned_income)
    else:
        after_student__1 = (student_monthly_limit)
    after_student = ((after_irregular - after_student__1))
    if (non_needs_based_unearned_remainder <= Money(Integer(2000))):
        after_general_20__1 = (non_needs_based_unearned_remainder)
    else:
        after_general_20__1 = (Money(Integer(2000)))
    after_general_20 = ((after_student - after_general_20__1))
    if (after_general_20 <= Money(Integer(6500))):
        after_65__1 = (after_general_20)
    else:
        after_65__1 = (Money(Integer(6500)))
    after_65 = ((after_general_20 - after_65__1))
    after_irwe = ((after_65 - impairment_work_expenses))
    after_half = ((after_irwe * decimal_of_string("1/2")))
    after_blind = ((after_half - blind_work_expenses))
    adjusted_earned_income = ((after_blind - self_support_exclusion))
    return ExclusionChainDecision(after_65 = after_65, after_irwe = after_irwe, after_half = after_half, after_blind = after_blind, adjusted_earned_income = adjusted_earned_income)
